# Generated by Django 3.1.5 on 2021-01-27 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=32)),
                ('strength', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=100)),
                ('enrollee', models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
