# Generated by Django 3.1.5 on 2021-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='jdgn', unique=True),
            preserve_default=False,
        ),
    ]
