# Generated by Django 3.1.5 on 2021-02-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollee',
        ),
        migrations.CreateModel(
            name='Track_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('Track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='relation',
            field=models.ManyToManyField(through='courses.Track_Course', to='courses.Course'),
        ),
    ]
