# Generated by Django 3.1.5 on 2021-02-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210128_1227'),
        ('courses', '0004_auto_20210209_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track_course',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='track_course',
            old_name='Track',
            new_name='track',
        ),
        migrations.RemoveField(
            model_name='profile_course',
            name='Profile',
        ),
        migrations.AddField(
            model_name='course',
            name='relation',
            field=models.ManyToManyField(through='courses.Profile_Course', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='profile_course',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_course',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
    ]
