# Generated by Django 2.2.5 on 2021-02-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210209_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course')),
                ('pre_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_course', to='courses.Course')),
            ],
        ),
    ]
