# Generated by Django 2.2.5 on 2021-02-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_course',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('C', 'Creditted')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
