# Generated by Django 3.1.5 on 2021-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_profile_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], max_length=10),
        ),
    ]
