# Generated by Django 3.1.5 on 2021-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210211_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='practicals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.IntegerField(default=0),
        ),
    ]
