# Generated by Django 2.2.5 on 2021-01-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='sljgn', max_length=50),
            preserve_default=False,
        ),
    ]
