# Generated by Django 3.1.5 on 2021-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210128_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(default=1),
        ),
    ]
