# Generated by Django 3.1.5 on 2021-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
