# Generated by Django 3.1.5 on 2021-04-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
    ]
